# Generated by Django 5.0.5 on 2024-07-17 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Foto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='OleoFiltro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oleo', models.CharField(max_length=120)),
                ('filtro', models.CharField(max_length=120)),
                ('km_oleo', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='endereço do email')),
                ('telefone', models.CharField(blank=True, max_length=15, null=True)),
                ('endereco', models.CharField(max_length=200)),
                ('cfp', models.CharField(max_length=20)),
                ('rg', models.CharField(max_length=13)),
                ('gen', models.CharField(choices=[('M', 'MASCULINO'), ('F', 'FEMININO')], max_length=200)),
            ],
        ),
    ]
