# Generated by Django 5.0.5 on 2024-08-06 23:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaboDeVela',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cabo_de_vela', models.CharField(max_length=120)),
                ('km_cabo_vela', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CorreiaDentalha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correia_dentalha', models.CharField(max_length=120)),
                ('km_correia', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='FiltroArCondicionado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filtro_ar_condicionado', models.CharField(max_length=120)),
                ('km_filtro_ar_condicionado', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='FiltroGas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filtro_gas', models.CharField(max_length=120)),
                ('km_filtro', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PastilhaDeFreio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pastilha', models.CharField(max_length=120)),
                ('km_pastilha', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Pneu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pneu', models.CharField(max_length=120)),
                ('km_pneu', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Carro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=7)),
                ('modelo', models.CharField(max_length=60)),
                ('ano', models.IntegerField()),
                ('kilometragem', models.IntegerField()),
                ('tipo', models.CharField(choices=[('G', 'Gas'), ('P', 'Gasolina'), ('E', 'Etanol')], max_length=50)),
                ('fotoFK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='FotoCarroFK', to='App.foto')),
                ('usuarioFK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='UserCarroFK', to='App.user')),
            ],
        ),
        migrations.CreateModel(
            name='Manutencao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carroFK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ManutencaoCarro', to='App.carro')),
                ('correiaDentalhaFK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ManutencaoCorreiaDentalhaFK', to='App.correiadentalha')),
                ('filtroArCondicionadoFK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ManutencaoFiltroArCondicionadoFK', to='App.filtroarcondicionado')),
                ('filtroGasFK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ManutencaoFiltroGasFK', to='App.filtrogas')),
                ('oleoFiltroFK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ManutencaoOleoFiltroFK', to='App.oleofiltro')),
                ('pastilhaDeFreioFK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ManutencaoPastilhaDeFreioFK', to='App.pastilhadefreio')),
                ('pneuFK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ManutencaoPneuFK', to='App.pneu')),
            ],
        ),
    ]
