# Generated by Django 5.0.5 on 2024-08-07 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_cabodevela_correiadentalha_filtroarcondicionado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='manutencao',
            name='manutencao',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
