# Generated by Django 5.0.5 on 2024-08-08 00:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_manutencao_manutencao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Imposto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placaImposto', models.CharField(max_length=7)),
                ('licenciamento', models.IntegerField()),
                ('ipva', models.IntegerField()),
                ('seguro', models.IntegerField()),
                ('rastreador', models.IntegerField()),
                ('financiamento', models.IntegerField()),
                ('manutencaoFK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ImpostoManutencao', to='App.manutencao')),
            ],
        ),
    ]
