# Generated by Django 5.0.5 on 2024-08-09 00:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_imposto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manutencao',
            name='correiaDentalhaFK',
        ),
        migrations.RemoveField(
            model_name='manutencao',
            name='filtroArCondicionadoFK',
        ),
        migrations.RemoveField(
            model_name='manutencao',
            name='filtroGasFK',
        ),
        migrations.RemoveField(
            model_name='manutencao',
            name='oleoFiltroFK',
        ),
        migrations.RemoveField(
            model_name='manutencao',
            name='pastilhaDeFreioFK',
        ),
        migrations.RemoveField(
            model_name='manutencao',
            name='pneuFK',
        ),
        migrations.CreateModel(
            name='ManuOleoFiltro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manutencaoFK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ManutOleoFiltro', to='App.manutencao')),
                ('oleoFiltroFK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ManutOleoFiltroFK', to='App.oleofiltro')),
            ],
        ),
    ]
